name: task-2
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://database:5432/task-2?user=postgres
      DATABASE_DRIVER: org.postgresql.Driver
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres
    environment:
      POSTGRES_DB: task-2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
